services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Use Lexik JWT manager in AuthService (no JWT_SECRET needed)
  App\Service\AuthService:
    arguments:
      $jwtManager: "@lexik_jwt_authentication.jwt_manager"
